apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: virtualenvironments.seamed.releasify.io
spec:
  group: seamed.releasify.io
  names:
    kind: VirtualEnvironment
    plural: virtualenvironments
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            http:
              items:
                properties:
                  destinationRoute:
                    properties:
                      host:
                        type: string
                      port:
                        properties:
                          number:
                            format: int32
                            type: integer
                        type: object
                    type: object
                  match:
                    items:
                      properties:
                        authority:
                          type: object
                        gateways:
                          items:
                            type: string
                          type: array
                        headers:
                          type: object
                        method:
                          type: object
                        port:
                          format: int32
                          type: integer
                        scheme:
                          type: object
                        uri:
                          type: object
                      type: object
                    type: array
                type: object
              type: array
            services:
              items:
                properties:
                  host:
                    type: string
                  labels:
                    type: object
                type: object
              type: array
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
