apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: entrypoints.seamed.releasify.io
spec:
  group: seamed.releasify.io
  names:
    kind: Entrypoint
    plural: entrypoints
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            defaultVirtualEnvironment:
              type: string
            servers:
              items:
                properties:
                  hosts:
                    items:
                      type: string
                    type: array
                  port:
                    properties:
                      name:
                        type: string
                      number:
                        format: int32
                        type: integer
                      protocol:
                        type: string
                    type: object
                  tls:
                    properties:
                      mode:
                        type: string
                    type: object
                type: object
              type: array
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
